version: '3.8'
services:
  db:
    image: postgres:12.14-alpine
    restart: always
    networks:
      - main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/01-create_database_and_tables.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
networks:
  main: